version: '3.8'

services:
  gateway-service:
    build:
      context: ./gateway/
      dockerfile: gateway.dockerfile
    ports:
      - "8080:8080"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/gateway_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres
      - user-service
      - order-service

  user-service:
    build:
      context: ./user/
      dockerfile: user.dockerfile
    ports:
      - "8082:8082"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/user_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres

  order-service:
    build:
      context: ./order/
      dockerfile: order.dockerfile
    ports:
      - "8083:8083"
    environment:
      - TZ=America/Sao_Paulo
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/order_service
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
    volumes:
      - ./logs:/app/logs
    depends_on:
      - postgres

  postgres:
    image: postgres:14
    container_name: my_postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  django:
    build:
      context: ./payment/
      dockerfile: django.dockerfile
    command: python payment/manage.py runserver 0.0.0.0:8000
    ports: 
     - 8000:8000
    volumes: 
     - .:/app
    depends_on:
      - postgres

volumes:
  postgres_data:
