spring:
  cloud:
    gateway:
      routes:
        - id: user-service
          uri: http://localhost:8082
          predicates:
            - Path=/users, /users/**
          filters:
            - RewritePath=/users(?<segment>/.*)?, /api/v1/users${segment}